## libmatroska Makefile
## (c) 2002 Steve Lhomme
## This software is licensed under the LGPL, see LICENSE.LGPL

all: endian
	echo "Making endianess tests"
	(cd endian; make)
clean:
	echo "Cleaning all tests"
	(cd endian; make $@)
