name: "Linux+gcc13"
on:
  push:
    branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build_libmatroska:
    name: libmatroska with gcc13
    runs-on: ubuntu-latest
    env:
      CMAKE_OPTIONS: -DCMAKE_CXX_EXTENSIONS=OFF
      CMAKE_MATROSKA_OPTIONS: -DBUILD_EXAMPLES=ON
    steps:
      - uses: lukka/get-cmake@latest

      - name: Get pushed code
        uses: actions/checkout@v3

      - name: Checkout libebml
        uses: actions/checkout@v3
        with:
          repository: Matroska-Org/libebml
          path: libebml
          # minimum version we support ref: 'release-1.4.3'

      - name: Configure libebml
        run: cmake -S libebml -B libebml/_build ${{ env.CMAKE_OPTIONS }}
        env:
          CC:  gcc-13
          CXX: g++-13

      - name: Build libebml
        run: cmake --build libebml/_build --parallel

      - name: Install libebml
        run: cmake --install libebml/_build --prefix ${GITHUB_WORKSPACE}/_built

      - name: Configure CMake
        run: cmake -S . -B _build  ${{ env.CMAKE_OPTIONS }} ${{ env.CMAKE_MATROSKA_OPTIONS }} -DEBML_DIR="${GITHUB_WORKSPACE}/_built/lib/cmake/EBML"
        env:
          CC:  gcc-13
          CXX: g++-13

      - name: Build
        run: cmake --build _build --parallel

      - name: Test installation
        run: cmake --install _build --prefix ${GITHUB_WORKSPACE}/_built
